name: Docker Image CI

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag sandalisubasinghe95/node:latest
      - name: Push the Docker Image
        run: docker login -u sandalisubasinghe95 -p ${{secrets.DOCKER_TOKEN }} && docker push sandalisubasinghe95/node:latest
